### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by FinalPacket** [undersquire/Hades#23]
**Describe the bug**
VelocityEvent throws NPEs on assert lines

**To Reproduce**
go on a 1.8 server w/ strikepractice *which you claimed to tested* whether it is you causing it or the citizens npcs

> [20:07:19 ERROR]: Could not pass event PlayerVelocityEvent to Hades v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:231) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at me.apex.hades.listeners.VelocityListener.onVelocity(VelocityListener.java:24) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        ... 10 more
[20:07:19 ERROR]: Could not pass event PlayerVelocityEvent to Hades v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:231) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at me.apex.hades.listeners.VelocityListener.onVelocity(VelocityListener.java:24) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        ... 10 more
>

**Expected behavior**
for it not to throw errors spamming the entirety.

**Screenshots**
![image](https://user-images.githubusercontent.com/19363974/84429563-45e83c00-ac20-11ea-9b8e-9b7a43d2a81f.png)
![image](https://user-images.githubusercontent.com/19363974/84429607-5b5d6600-ac20-11ea-9fd1-3e2fce07f770.png)

**Server Version:**
1.8.8

**Plugin Version:**
1.0.3-pre-release

**Additional context**
++

**Comment by undersquire** [comment]
Thank you for reporting these issues! We will look into them ASAP.

PS: Please report issues here from now on first before writing a review about them! Thanks!

**Comment by Tecnio** [comment]
Hey, I have seen this post newly, we have never claimed we supported strike practice!

**Comment by FinalPacket** [comment]
> 
> 
> Hey, I have seen this post newly, we have never claimed we supported strike practice!

you said you supported 1.8, I've don't think I've ever seen any other anticheat whether new or old have problem supporting citizen npcs (except for the ones that make playerdata for them because why not)

**Comment by Tecnio** [comment]
Thats the point we never said that. You thought our was like the others. And yes our anticheat uses player data.

**Comment by LIWKK** [comment]
> 
> 
> Thats the point we never said that. You thought our was like the others. And yes our anticheat uses player data.

Are u braindead or what, not to be rude, but you can check if the opponent has playerdata 🥇

**Comment by Tecnio** [comment]
> > Thats the point we never said that. You thought our was like the others. And yes our anticheat uses player data.
> 
> Are u braindead or what, not to be rude, but you can check if the opponent has playerdata 🥇

I know that. But thats not the point the point is we never said that i know we can fix it. Anyways the base is being recoded so yea everything should be fixed and the code should be cleaner.
