### ISSUE TITLE
Falses

### ISSUE THREAD

**Issue by UnknownMyName** [undersquire/Hades#9]
FALSE:

Autoclicker A false when digging. (in one sec you can make 100 falses)
Autoclicker C and Timer A false when you lagging.
Aim C false I don't know how.
Fly C&F false when use a ladder.
Speed E false when fly in gamemode or /fly.
Speed C false when you teleport.
NoFall A and Fly B false when spamming ghost block.

-----
BYPASS:

With sigma disablers we can use all cheats like speed, fly, phase, scaffold, nofall etc
Without disablers we can use Speed (SlowHop, All YPort, AGC, TestSpeed), NoSlow, InvMove, Sneak, Phase (NoClip, unfull),  

(test done in 15 minutes with only 1 client (free))

(btw I did not test the combat)

**Comment by UnknownMyName** [comment]
LIQUIDBOUNCE:
Fly (AAC3.3.12-GLIDE, NeruxVace)
Speed (YPort2, NCPYport, Boost, onGround, AACHop3.3.13, AACLHop3, AACGround2, AACYPort, AACYPort2, AACPort, SpartanYPort, SpectrelOnGround)
NoSlow
InvMove
NoWeb
NoFall (noGround, AAC, LAAC)

Criticals (Packet, NoGround, Hop, TPHop, Jump, LowJump)
HitBoxes
Killaura (default value)
Velocity (AAC, AACPush, Reverse, SmoothReverse, Jump)

(Timer detection are very very very slow)

**Comment by UnknownMyName** [comment]
`[20:58:46] [Netty Epoll Server IO #1/WARN]: java.lang.reflect.InvocationTargetException
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at me.purplex.packetevents.event.manager.EventManager.callEvent(EventManager.java:31)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at me.purplex.packetevents.injector.PlayerInject_1_8$1.channelRead(PlayerInject_1_8.java:22)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[20:58:46] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at me.apex.hades.check.impl.combat.aura.AuraB.onPacket(AuraB.java:22)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at me.apex.hades.listeners.NetworkListener.lambda$1(NetworkListener.java:34)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	at me.apex.hades.listeners.NetworkListener.onPacketReceive(NetworkListener.java:34)
[20:58:46] [Netty Epoll Server IO #1/WARN]: 	... 25 more`

**Comment by undersquire** [comment]
Thank you for reporting these issues! However, I have tested and the Sigma disablers are not disabling any checks for me whatsoever. I'm not sure if that was because of an issue I just fixed, so I'll retest everything you reported and see if it is still an issue. Make sure you are using regular spigot and not any forked spigots (like paperspigot).

**Comment by UnknownMyName** [comment]
I have try with spigot 1.8.8

**Comment by undersquire** [comment]
So I have been testing and experimenting with sigma and those bypasses and here are the results. The disablers on sigma have no affect against the anticheat. The reason those speeds bypass is because they are barely an advantage and are barely faster than legit players. Phase, Inventory Move, NoClip, NoSlow, Sneak, hitboxes (reach) and Velocity are all bypassing because I have no checks for those at the moment (or the checks I have are disabled). I also dont have any glide checks which is why LiquidBounce bypasses. I am going to work on glide checks soon as that is an advantage. Timer check is slow to prevent false positives, which I dont see how you were able to false it considering I have tested it against 1000+ ping before without issues. I will continue to experiment and patch these smaller, less advantage giving hacks but for now they will bypass. Thanks for reporting these issues!

**Comment by Tecnio** [comment]
And btw i fixed some of your issues i am waiting for pull request rn!
